#!/usr/bin/env bash

source /etc/AIInAAL/AIInAAL_path
aiinaalpkg=Auto1111

AIInAAL_update_Auto1111 () {
  cd $AIInAALdir/$aiinaalpkg
  git fetch --all
  git branch backup-master
  git reset --hard origin/master
  git pull
  rm ./libref-$aiinaalpkg*
  rm ./requirements_$aiinaalpkg*
  wget https://raw.githubusercontent.com/JT-Gresham/AIInAAL/main/Auto1111/libref-$aiinaalpkg
  wget https://raw.githubusercontent.com/JT-Gresham/AIInAAL/main/Auto1111/user_customize_$aiinaalpkg_example.sh
  wget https://raw.githubusercontent.com/JT-Gresham/AIInAAL/main/Auto1111/requirements_$aiinaalpkg.txt
  pip install -r requirements_$aiinaalpkg.txt
  if grep -Fxq "import intel_extension_for_pytorch as ipex" launch.py
    then
      echo "Intel extensions found in launch.py...skipping"
    else
      sed -i 's|from modules import launch_utils|import intel_extension_for_pytorch as ipex\nimport intel_extension_for_transformers\nfrom modules import launch_utils\n|g' launch.py
  fi

rm -R "$AIInAALdir/$aiinaalpkg/models/Stable-diffusion"
#rm -R "$AIInAALdir/$aiinaalpkg/models/loras"
#rm -R "$AIInAALdir/$aiinaalpkg/models/clip_vision"
#rm -R "$AIInAALdir/$aiinaalpkg/models/controlnet"
#rm -R "$AIInAALdir/$aiinaalpkg/wildcards"
#rm -R "$AIInAALdir/$aiinaalpkg/sdxl_styles"
rm -R "$AIInAALdir/$aiinaalpkg/models/VAE"
rm -R "$AIInAALdir/$aiinaalpkg/models/VAE_approx"
#rm -R "$AIInAALdir/$aiinaalpkg/output"
ln -sf "$AIInAALdir/shared/checkpoints/t2i" "$AIInAALdir/$aiinaalpkg/models/Stable-diffusion"
#ln -sf "$AIInAALdir/shared/loras/t2i" "$AIInAALdir/$aiinaalpkg/models/loras"
#ln -sf "$AIInAALdir/shared/clip_vision" "$AIInAALdir/$aiinaalpkg/models/clip_vision"
#ln -sf "$AIInAALdir/shared/controlnet" "$AIInAALdir/$aiinaalpkg/models/controlnet"
#ln -sf "$AIInAALdir/shared/wildcards/Fooocus/" "$AIInAALdir/$aiinaalpkg/wildcards"
#ln -sf "$AIInAALdir/shared/sdxl_styles/$aiinaalpkg" "$AIInAALdir/$aiinaalpkg/sdxl_styles"
ln -sf "$AIInAALdir/shared/VAEs/t2i/vae/" "$AIInAALdir/$aiinaalpkg/models/VAE"
ln -sf "$AIInAALdir/shared/VAEs/t2i/vae_approx/" "$AIInAALdir/$aiinaalpkg/models/VAE_approx"
#ln -sf "$AIInAALdir/shared/output/Auto1111/" "$AIInAALdir/$aiinaalpkg/output"
cd $pdirectory
$AIInAALdir/$aiinaalpkg/user_customize_$aiinaalpkg.sh
cd $AIInAALdir/$aiinaalpkg
}

Auto1111-exit () {
    kill $(pidof python $AIInAALdir/$aiinaalpkg)
}
