#!/usr/bin/env bash

source /etc/AIInAAL/AIInAAL_path
aiinaalpkg=SwarmUI

AIInAAL_update_SwarmUI () {
  cd $AIInAALdir/$aiinaalpkg
  git fetch --all
  git branch backup-master
  git reset --hard origin/master
  git pull
  rm ./libref-$aiinaalpkg*
  rm ./requirements_$aiinaalpkg*
  wget https://raw.githubusercontent.com/JT-Gresham/AIInAAL/main/SwarmUI/libref-$aiinaalpkg
  wget https://raw.githubusercontent.com/JT-Gresham/AIInAAL/main/SwarmUI/user_customize_$aiinaalpkg_example.sh
  wget https://raw.githubusercontent.com/JT-Gresham/AIInAAL/main/SwarmUI/requirements_$aiinaalpkg.txt
  AIInAAL update Torch
  pip install -r requirements_$aiinaalpkg.txt
  AIInAAL update Intel
if grep -Fxq "https://download.pytorch.org/whl/xpu" $AIInAALdir/$aiinaalpkg/launchtools/comfy-install-linux.sh
    then
        echo "JT correction entry found in comfy-install-linux.sh ...skipping"
    else
        sed -i 's|GPU_TYPE=$1|GPU_TYPE=xpu|g' $AIInAALdir/$aiinaalpkg/launchtools/comfy-install-linux.sh
        sed -i 's|&& [ "$GPU_TYPE" != "nv" ]|&& [ "$GPU_TYPE" != "nv" ] && [ "$GPU_TYPE" != "xpu" ]|g' $AIInAALdir/$aiinaalpkg/launchtools/comfy-install-linux.sh
        sed -i 's|--index-url https://download.pytorch.org/whl/rocm7.1|--index-url https://download.pytorch.org/whl/rocm7.1\nelif [ "$GPU_TYPE" == "xpu" ]; then\n    echo "install xpu torch..."\n    $python -s -m pip install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/xpu|g' $AIInAALdir/$aiinaalpkg/launchtools/comfy-install-linux.sh
fi
  #if grep -Fxq "https://download.pytorch.org/whl/cu121" launch.py
  #  then
  #    echo "URL for Intel version of pytorch found in launch.py...skipping"
  #  else
  #    sed -i 's|https://download.pytorch.org/whl/cu121|https://pytorch-extension.intel.com/release-whl/stable/xpu/us/|g' $AIInAALdir/$aiinaalpkg/launch.py
  #fi
  #if grep -Fxq "torch==2.1.0 torchvision==0.16.0" launch.py
  #  then
  #    echo "Intel versions of pytorch-related packages found in launch.py...skipping"
  #  else
  #    sed -i 's|torch==2.1.0 torchvision==0.16.0|torch>=2.3.1 torchvision>=0.18.1 torchaudio>=2.3.1 intel-extension-for-pytorch>=2.3.110+xpu|g' launch.py
  #fi
  #if grep -Fxq "torchsde==0.2.6" requirements_versions.txt
  #  then
  #    echo "torchsde version fix found in requirements_versions.txt...skipping"
  #  else
  #    sed -i 's|torchsde==0.2.6|torchsde>=0.2.6|g' requirements_versions.txt
  #fi
  #if grep -Fxq "transformers==4.30.2" requirements_versions.txt
  #  then
  #    echo "torchsde version fix found in requirements_versions.txt...skipping"
  #  else
  #    sed -i 's|transformers==4.30.2|transformers>=4.34.0|g' requirements_versions.txt
  #fi
  #if grep -Fxq "accelerate==0.21.0" requirements_versions.txt
  #  then
  #    echo "accelerate version fix found in requirements_versions.txt...skipping"
  #  else
  #    sed -i 's|accelerate==0.21.0|accelerate>=0.21.0|g' requirements_versions.txt
  #fi
  #if grep -Fxq "scipy==1.9.3" requirements_versions.txt
  #  then
  #    echo "scipy version fix found in requirements_versions.txt...skipping"
  #  else
  #    sed -i 's|scipy==1.9.3|scipy>=1.9.3|g' requirements_versions.txt
  #fi

# FIX DOTNET
rm $AIInAALdir/AIInAAL_env/bin/dotnet
ln -sf $AIInAALdir/AIInAAL_env/lib/python3.11/site-packages/dotnetcore2/ $AIInAALdir/AIInAAL_env/lib/python3.11/dotnetcore2
ln -sf $AIInAALdir/AIInAAL_env/lib/python3.11/dotnetcore2/bin/dotnet $AIInAALdir/AIInAAL_env/bin/dotnet

rm -R "$AIInAALdir/$aiinaalpkg/Models/Stable-Diffusion"
rm -R "$AIInAALdir/$aiinaalpkg/Models/Lora"
rm -R "$AIInAALdir/$aiinaalpkg/Models/clip_vision"
rm -R "$AIInAALdir/$aiinaalpkg/Models/controlnet"
#rm -R "$AIInAALdir/$aiinaalpkg/wildcards"
#rm -R "$AIInAALdir/$aiinaalpkg/sdxl_styles"
rm -R "$AIInAALdir/$aiinaalpkg/Models/VAE"
rm -R "$AIInAALdir/$aiinaalpkg/Models/VAE-approx"
rm -R "$AIInAALdir/$aiinaalpkg/Data/Wildcards"
rm -R "$AIInAALdir/$aiinaalpkg/Output"
mkdir -p $AIInAALdir/$aiinaalpkg/Output/local
ln -sf "$AIInAALdir/shared/checkpoints/t2i" "$AIInAALdir/$aiinaalpkg/Models/Stable-Diffusion"
ln -sf "$AIInAALdir/shared/loras/t2i" "$AIInAALdir/$aiinaalpkg/Models/Lora"
ln -sf "$AIInAALdir/shared/clip_vision" "$AIInAALdir/$aiinaalpkg/Models/clip_vision"
ln -sf "$AIInAALdir/shared/controlnet" "$AIInAALdir/$aiinaalpkg/Models/controlnet"
#ln -sf "$AIInAALdir/shared/wildcards/$aiinaalpkg" "$AIInAALdir/$aiinaalpkg/wildcards"
#ln -sf "$AIInAALdir/shared/sdxl_styles/$aiinaalpkg" "$AIInAALdir/$aiinaalpkg/sdxl_styles"
ln -sf "$AIInAALdir/shared/VAEs/t2i/vae/" "$AIInAALdir/$aiinaalpkg/Models/VAE"
ln -sf "$AIInAALdir/shared/VAEs/t2i/vae_approx/" "$AIInAALdir/$aiinaalpkg/Models/VAE-approx"
ln -sf "$AIInAALdir/shared/wildcards/" "$AIInAALdir/$aiinaalpkg/Data/Wildcards"
ln -sf "$AIInAALdir/shared/output/SwarmUI/" "$AIInAALdir/$aiinaalpkg/Output/local/raw"
cd $pdirectory
$AIInAALdir/$aiinaalpkg/user_customize_$aiinaalpkg.sh
cd $AIInAALdir/$aiinaalpkg
}

SwarmUI-exit () {
    kill $(pidof python $AIInAALdir/$aiinaalpkg)
}
