#!/usr/bin/env bash

source /etc/AIInAAL/AIInAAL_path
aiinaalpkg=DeFooocus

AIInAAL_update_DeFooocus () {
  cd $AIInAALdir/$aiinaalpkg
  git pull
  wget https://raw.githubusercontent.com/JT-Gresham/AIInAAL/main/DeFooocus/libref-$aiinaalpkg
  wget https://raw.githubusercontent.com/JT-Gresham/AIInAAL/main/DeFooocus/requirements_$aiinaalpkg.txt
  pip install -r requirements_DeFooocus.txt
#### DEBUG - CAN'T FIND launch.py #####
pwd
  if grep -Fxq "import intel_extension_for_pytorch as ipex" $AIInAALdir/$aiinaalpkg/launch.py
    then
      echo "Intel extensions found in launch.py...skipping"
    else
      sed -i 's|import ssl|import ssl\n\nimport torch\nimport torch\nimport torchvision.models as models\n\nmodel = models.resnet50(pretrained=True)\nmodel.eval()\ndata = torch.rand(1, 3, 224, 224)\n\nimport intel_extension_for_pytorch as ipex\nmodel = model.to('xpu')\ndata = data.to('xpu')\nmodel = ipex.optimize(model)\n\nwith torch.no_grad():
\nmodel(data)\n\nimport openvino\n|g' $AIInAALdir/$aiinaalpkg/launch.py
  fi
  if grep -Fxq "https://download.pytorch.org/whl/cu121" $AIInAALdir/$aiinaalpkg/launch.py
    then
      echo "URL for Intel version of pytorch found in launch.py...skipping"
    else
      sed -i 's|https://download.pytorch.org/whl/cu121|https://developer.intel.com/ipex-whl-stable-xpu/|g' $AIInAALdir/$aiinaalpkg/launch.py
  fi
  if grep -Fxq "torch==2.1.0 torchvision==0.16.0" $AIInAALdir/$aiinaalpkg/launch.py
    then
      echo "Intel versions of pytorch-related packages found in launch.py...skipping"
    else
      sed -i 's|torch==2.1.0 torchvision==0.16.0|torch>=2.1.0.post3+cxx11.abi torchvision>=0.16.0.post3+cxx11.abi torchaudio>=2.1.0.post3+cxx11.abi intel-extension-for-pytorch>=2.1.40+xpu|g' $AIInAALdir/$aiinaalpkg/launch.py
  fi
  if grep -Fxq "torchsde>=0.2.5" requirements_versions.txt
    then
      echo "torchsde version fix found in requirements_versions.txt...skipping"
    else
      sed -i 's|torchsde==0.2.6|torchsde>=0.2.6|g' requirements_versions.txt
  fi
  if grep -Fxq "transformers>=4.34.0" requirements_versions.txt
    then
      echo "torchsde version fix found in requirements_versions.txt...skipping"
    else
      sed -i 's|transformers==4.30.2|transformers>=4.34.0|g' requirements_versions.txt
  fi
rm -R "$AIInAALdir/$aiinaalpkg/models/checkpoints"
rm -R "$AIInAALdir/$aiinaalpkg/models/loras"
rm -R "$AIInAALdir/$aiinaalpkg/wildcards"
rm -R "$AIInAALdir/$aiinaalpkg/sdxl_styles"
ln -sf "$AIInAALdir/shared/checkpoints/t2i" "$AIInAALdir/$aiinaalpkg/models/checkpoints"
ln -sf "$AIInAALdir/shared/loras/t2i" "$AIInAALdir/$aiinaalpkg/models/loras"
ln -sf "$AIInAALdir/shared/wildcards/$aiinaalpkg" "$AIInAALdir/$aiinaalpkg/wildcards"
ln -sf "$AIInAALdir/shared/sdxl_styles/$aiinaalpkg" "$AIInAALdir/$aiinaalpkg/sdxl_styles"
cd $pdirectory
$AIInAALdir/$aiinaalpkg/user_customize_$aiinaalpkg.sh
}

Fooocus-exit () {
    kill $(pidof python $AIInAALdir/$aiinaalpkg)
}
