#!/usr/bin/env bash

source /etc/AIInAAL/AIInAAL_path

echo "Running librefgen..."
cd $AIInAALdir
echo "Regenerating LIBREF..."
echo "pdirectory=$pdirectory" > $AIInAALdir/libref
echo "AIInAALdir=$AIInAALdir" >> $AIInAALdir/libref
echo "" >> $AIInAALdir/libref
echo "export LD_LIBRARY_PATH=$AIInAALdir_env/lib" >> $AIInAALdir/libref
#echo "export CUDA_PATH=$AIInAALdir_env/lib/python3.11/site-packages/nvidia" >> $AIInAALdir/libref
echo "export USE_XETLA=OFF" >> $AIInAALdir/libref
echo "export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1" >> $AIInAALdir/libref
echo "export SYCL_CACHE_PERSISTENT=1" >> $AIInAALdir/libref
echo "export LLM_DIR=$AIInAALdir/AIInAAL_env/lib/python3.11/site-packages/ipex_llm" >> $AIInAALdir/libref
echo "source /opt/intel/oneapi/setvars.sh" >> $AIInAALdir/libref
echo "source $AIInAALdir_env/bin/ipex-llm-init -g --device Arc" >> $AIInAALdir/libref

echo "AIInAAL_update () {" >> $AIInAALdir/libref
echo "    cd $AIInAALdir" >> $AIInAALdir/libref
echo "    git switch main" >> $AIInAALdir/libref
echo "    git reset --hard HEAD" >> $AIInAALdir/libref
echo "    git pull" >> $AIInAALdir/libref
#echo "    pip install --upgrade -no-dependencies ipex-llm[xpu]" >> $AIInAALdir/libref
echo "}" >> $AIInAALdir/libref
echo "LIBREF regenerated."
