#!/usr/bin/env bash

source /etc/AIInAAL/AIInAAL_path

echo "Running librefgen..."
cd $AIInAALdir
echo "Regenerating LIBREF..."
echo "pdirectory=$pdirectory" > $AIInAALdir/libref
echo "AIInAALdir=$AIInAALdir" >> $AIInAALdir/libref
echo "" >> $AIInAALdir/libref
echo "export LD_LIBRARY_PATH=$AIInAALdir_env/lib" >> $AIInAALdir/libref
#echo "export LLM_DIR=$AIInAALdir_env/lib/python3.11/site-packages/intel_extension_for_pytorch/llm" >> $AIInAALdir/libref
#echo "rm \"$AIInAALdir/AIInAAL_env/lib/python3.11/site-packages/ipex_llm\"" >> $AIInAALdir/libref
#echo "ln -sf \"$AIInAALdir_env/lib/python3.11/site-packages/intel_extension_for_pytorch/llm/\" \"$AIInAALdir/AIInAAL_env/lib/python3.11/site-packages/ipex_llm\"" >> $AIInAALdir/libref
#echo "export LLM_DIR=$AIInAALdir/AIInAAL_env/lib/python3.11/site-packages/ipex_llm" >> $AIInAALdir/libref
echo "export USE_XETLA=OFF" >> $AIInAALdir/libref
echo "export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1" >> $AIInAALdir/libref
echo "export SYCL_CACHE_PERSISTENT=1" >> $AIInAALdir/libref
echo "source /opt/intel/oneapi/setvars.sh" >> $AIInAALdir/libref
echo "source $pdirectory/AIInAAL/AIInAAL_env/bin/ipex-llm-init -g --device Arc" >> $AIInAALdir/libref

echo "AIInAAL_update () {" >> $AIInAALdir/libref
echo "    Correcting any BS WINBLOWS carriage return entries in bash scripts..." >> $AIInAALdir/libref
echo "    cd $AIInAALdir/Scripts" >> $AIInAALdir/libref
echo "    for file in *.sh" >> $AIInAALdir/libref
echo "      do" >> $AIInAALdir/libref
echo "      sed -i 's/\r//' $file" >> $AIInAALdir/libref
echo "    done" >> $AIInAALdir/libref
echo "    cd $AIInAALdir" >> $AIInAALdir/libref
echo "    sed -i 's/\r//' $AIInAALdir/AIInAAL_install.sh" >> $AIInAALdir/libref
echo "    git switch main" >> $AIInAALdir/libref
echo "    git reset --hard HEAD" >> $AIInAALdir/libref
echo "    git pull" >> $AIInAALdir/libref
echo "    rm -Rf $AIInAALdir/AIInAAL_env/lib/python3.11/site-packages/~*" >> $AIInAALdir/libref
echo "    Scripts/librefgen" >> $AIInAALdir/libref
echo "    pip install --upgrade pip" >> $AIInAALdir/libref
echo "    AIInAAL_update_Intel" >> $AIInAALdir/libref
echo "}" >> $AIInAALdir/libref

echo "AIInAAL_update_Intel () {" >> $AIInAALdir/libref
echo "    pip install --upgrade -r $AIInAALdir/Scripts/intel_requirements.txt" >> $AIInAALdir/libref
echo "}" >> $AIInAALdir/libref
echo "LIBREF regenerated."
