#!/usr/bin/env bash

source /etc/AIInAAL/AIInAAL_path
aiinaalpkg=Lumina-T2X

AIInAAL_update_Lumina-T2X () {
  cd $AIInAALdir/$aiinaalpkg
  git fetch --all
  git branch backup-master
  git reset --hard origin/master
  git pull
  rm ./libref-$aiinaalpkg*
  rm ./requirements_$aiinaalpkg*
  wget https://raw.githubusercontent.com/JT-Gresham/AIInAAL/main/Lumina-T2X/libref-$aiinaalpkg
  wget https://raw.githubusercontent.com/JT-Gresham/AIInAAL/main/Lumina-T2X/user_customize_$aiinaalpkg_example.sh
  wget https://raw.githubusercontent.com/JT-Gresham/AIInAAL/main/Lumina-T2X/requirements_$aiinaalpkg.txt
  pip install -r requirements_$aiinaalpkg.txt
  if grep -Fxq "import intel_extension_for_pytorch as ipex" $AIInAALdir/$aiinaalpkg/lumina_t2i/entry_point.py
    then
      echo "Intel extensions found in entry_point.py...skipping"
    else
      sed -i 's|import os|import os\n\nimport torch\nimport intel_extension_for_pytorch as ipex|g' $AIInAALdir/$aiinaalpkg/lumina_t2i/entry_point.py
  fi
  #if grep -Fxq "https://download.pytorch.org/whl/cu121" launch.py
  #  then
  #    echo "URL for Intel version of pytorch found in launch.py...skipping"
  #  else
  #    sed -i 's|https://download.pytorch.org/whl/cu121|https://pytorch-extension.intel.com/release-whl/stable/xpu/us/|g' $AIInAALdir/$aiinaalpkg/launch.py
  #fi
  #if grep -Fxq "torch==2.1.0 torchvision==0.16.0" launch.py
  #  then
  #    echo "Intel versions of pytorch-related packages found in launch.py...skipping"
  #  else
  #    sed -i 's|torch==2.1.0 torchvision==0.16.0|torch>=2.3.1 torchvision>=0.18.1 torchaudio>=2.3.1 intel-extension-for-pytorch>=2.3.110+xpu|g' launch.py
  #fi
  #if grep -Fxq "torchsde==0.2.6" requirements_versions.txt
  #  then
  #    echo "torchsde version fix found in requirements_versions.txt...skipping"
  #  else
  #    sed -i 's|torchsde==0.2.6|torchsde>=0.2.6|g' requirements_versions.txt
  #fi
  #if grep -Fxq "transformers==4.30.2" requirements_versions.txt
  #  then
  #    echo "torchsde version fix found in requirements_versions.txt...skipping"
  #  else
  #    sed -i 's|transformers==4.30.2|transformers>=4.34.0|g' requirements_versions.txt
  #fi
  #if grep -Fxq "accelerate==0.21.0" requirements_versions.txt
  #  then
  #    echo "accelerate version fix found in requirements_versions.txt...skipping"
  #  else
  #    sed -i 's|accelerate==0.21.0|accelerate>=0.21.0|g' requirements_versions.txt
  #fi
  #if grep -Fxq "scipy==1.9.3" requirements_versions.txt
  #  then
  #    echo "scipy version fix found in requirements_versions.txt...skipping"
  #  else
  #    sed -i 's|scipy==1.9.3|scipy>=1.9.3|g' requirements_versions.txt
  #fi
#rm -R "$AIInAALdir/$aiinaalpkg/models/checkpoints"
#rm -R "$AIInAALdir/$aiinaalpkg/models/loras"
#rm -R "$AIInAALdir/$aiinaalpkg/wildcards"
#rm -R "$AIInAALdir/$aiinaalpkg/sdxl_styles"
#rm -R "$AIInAALdir/$aiinaalpkg/models/vae"
#rm -R "$AIInAALdir/$aiinaalpkg/models/vae_approx"
#ln -sf "$AIInAALdir/shared/checkpoints/t2i" "$AIInAALdir/$aiinaalpkg/models/checkpoints"
#ln -sf "$AIInAALdir/shared/loras/t2i" "$AIInAALdir/$aiinaalpkg/models/loras"
#ln -sf "$AIInAALdir/shared/wildcards/Fooocus" "$AIInAALdir/$aiinaalpkg/wildcards"
#ln -sf "$AIInAALdir/shared/sdxl_styles/Fooocus" "$AIInAALdir/$aiinaalpkg/sdxl_styles"
#ln -sf "$AIInAALdir/shared/VAEs/t2i/vae/" "$AIInAALdir/$aiinaalpkg/models/vae"
#ln -sf "$AIInAALdir/shared/VAEs/t2i/vae_approx/" "$AIInAALdir/$aiinaalpkg/models/vae_approx"
cd $pdirectory
$AIInAALdir/$aiinaalpkg/user_customize_$aiinaalpkg.sh
}

Lumina-T2X-exit () {
    kill $(pidof python $AIInAALdir/$aiinaalpkg)
}
